# Initialization

In [ ]:
%%capture
!pip install scikit-network
!pip install leidenalg
!pip install pandas networkx
!pip install python-igraph

In [ ]:
from IPython.display import SVG
import numpy as np
from sknetwork.data import karate_club, painters, movie_actor
from sknetwork.clustering import Louvain, get_modularity
from sknetwork.linalg import normalize
from sknetwork.utils import get_membership
from sknetwork.visualization import svg_graph, svg_bigraph
import pandas as pd
import networkx as nx
import leidenalg as la
import igraph as ig
from google.colab import files
import matplotlib.pyplot as plt
from sklearn import metrics

# Centrality

In [ ]:
# Read adjacency matrix from CSV file
adj_matrix_df = pd.read_csv("Export_AdjacencyMatrix.csv", index_col=0)

In [ ]:
node_labels = adj_matrix_df.index.tolist()

In [ ]:
# Convert dataframe to a NumPy matrix
adj_matrix = adj_matrix_df.to_numpy()

# Create a directed graph from the adjacency matrix
g = nx.DiGraph(adj_matrix)

In [ ]:
# Compute betweenness centrality
centrality = nx.betweenness_centrality(g)

btw = list(centrality.values())

# Print the betweenness centrality scores
print(centrality)

{0: 0.00012459587213477447, 1: 0.0005264485016724181, 2: 0.000676712976849718, 3: 0.0, 4: 0.00031021878553710424, 5: 0.0008390840453440358, 6: 0.0011095423669259853, 7: 0.0, 8: 0.00044808300906239276, 9: 0.0011853095012194317, 10: 0.00021573788381437607, 11: 1.0265874494356641e-05, 12: 0.00644911701846214, 13: 0.0038527185874128343, 14: 0.00038913947414471437, 15: 0.00010599362705437671, 16: 0.001105031257236823, 17: 0.002736915977207304, 18: 0.0008565066624064676, 19: 0.0008865866263687449, 20: 0.007778205055757432, 21: 0.00022775851311376282, 22: 0.00046431384556557974, 23: 2.8164972394798915e-05, 24: 3.786971216642842e-06, 25: 0.0002909452094295429, 26: 0.0, 27: 0.00041478696121872435, 28: 0.0002602865315882785, 29: 0.0, 30: 0.0, 31: 0.005111958946590752, 32: 0.0, 33: 0.0, 34: 9.37347794863669e-05, 35: 0.0021430678995923123, 36: 0.0, 37: 0.00039844992970677635, 38: 7.789749387082995e-05, 39: 0.0012375355753446921, 40: 0.000988468606354005, 41: 0.008380317882851223, 42: 9.05901476114

In [ ]:
# Compute PageRank centrality
pagerank_centrality = nx.pagerank(g)

PR = list(pagerank_centrality.values())

# Print the PageRank centrality scores
print("PageRank Centrality:")
for node, score in pagerank_centrality.items():
    print(f"Node {node}: {score}")

In [ ]:
selected_node = 226 # USA

# Compute local PageRank for the selected node
local_pagerank_USA = nx.pagerank(g, personalization={selected_node: 1.0})

LPR_USA = list(local_pagerank_USA.values())

print(f"Local PageRank for {selected_node}:")
for node, score in local_pagerank_USA.items():
    print(f"Node {node}: {score}")

In [ ]:
selected_node = 47 # China

# Compute local PageRank for the selected node
local_pagerank_China = nx.pagerank(g, personalization={selected_node: 1.0})

LPR_China = list(local_pagerank_China.values())

print(f"Local PageRank for {selected_node}:")
for node, score in local_pagerank_China.items():
    print(f"Node {node}: {score}")

In [ ]:
selected_node = 110 # Italy

# Compute local PageRank for the selected node
local_pagerank_Italy = nx.pagerank(g, personalization={selected_node: 1.0})

LPR_Italy = list(local_pagerank_Italy.values())

print(f"Local PageRank for {selected_node}:")
for node, score in local_pagerank_Italy.items():
    print(f"Node {node}: {score}")

In [ ]:
result_df = pd.DataFrame({
    'node_labels': node_labels,
    'Betweenness': btw,
    'PageRank': PR,
    'LPR USA':LPR_USA,
    'LPR China':LPR_China,
    'LPR Italy':LPR_Italy
})

# Save the DataFrame to a CSV file
result_df.to_csv("centrality_results.csv", index=False)

In [ ]:
files.download("centrality_results.csv")

# Export Total

In [ ]:
# Load your adjacency matrix from CSV
adjacency_df = pd.read_csv("Export_AdjacencyMatrix.csv", index_col=0)  # Assuming row names are in the first column
adjacency = adjacency_df.values  # Extract the numeric values from DataFrame


In [ ]:
resolution_values = np.arange(0.5, 3.1, 0.1).tolist()
mod = []
for r in resolution_values:
  resolution_parameter = r # Adjust the resolution parameter as needed
  louvain = Louvain(resolution=resolution_parameter)
  labels = louvain.fit_predict(adjacency)
  labels_unique, counts = np.unique(labels, return_counts=True)
  mod.append(get_modularity(adjacency, labels))

# Find the maximum value in the list
max_mod = max(mod)

# Find the index of the maximum value in the list
max_index = mod.index(max_mod)
r_max = resolution_values[max_index]

print(f"Resolution yielding maximum modularity is {r_max}")
resolution_parameter = r_max # Adjust the resolution parameter as needed
louvain = Louvain(resolution=resolution_parameter)
labels = louvain.fit_predict(adjacency)
labels_unique, counts = np.unique(labels, return_counts=True)
mod.append(get_modularity(adjacency, labels))
print(labels_unique, counts)
print(get_modularity(adjacency, labels))

Resolution yielding maximum modularity is 0.9999999999999999
[0 1 2 3] [76 63 58 41]
0.292056800372797


In [ ]:
resolution_parameter = 0.9 # Adjust the resolution parameter as needed
louvain = Louvain(resolution=resolution_parameter)
labels = louvain.fit_predict(adjacency)
labels_unique, counts = np.unique(labels, return_counts=True)
print(f"Resolution = {resolution_parameter}")
print(labels_unique, counts)
print(get_modularity(adjacency, labels))
print("-------------")

Resolution = 0.9
[0 1 2 3 4 5] [92 86 44 16  3  1]
0.3278213490591159
-------------


In [ ]:
country_communities_df = pd.DataFrame({
    'Country': adjacency_df.index,
    'Community': labels
})

# Output the DataFrame
country_communities_df.to_csv("Louvain_Export_Python.csv", index=False)
files.download("Louvain_Export_Python.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# Mean Adjacency Matrix

In [ ]:
# Load your adjacency matrix from CSV
adjacency_df = pd.read_csv("MeanAdjacencyMatrix.csv", index_col=0, encoding='latin-1')  # Assuming row names are in the first column
adjacency = adjacency_df.values  # Extract the numeric values from DataFrame


In [ ]:
resolution_values = np.arange(0.5, 3.1, 0.1).tolist()
mod = []
for r in resolution_values:
  resolution_parameter = r # Adjust the resolution parameter as needed
  louvain = Louvain(resolution=resolution_parameter)
  labels = louvain.fit_predict(adjacency)
  labels_unique, counts = np.unique(labels, return_counts=True)
  mod.append(get_modularity(adjacency, labels))

# Find the maximum value in the list
max_mod = max(mod)

# Find the index of the maximum value in the list
max_index = mod.index(max_mod)
r_max = resolution_values[max_index]

print(f"Resolution yielding maximum modularity is {r_max}")
resolution_parameter = r_max # Adjust the resolution parameter as needed
louvain = Louvain(resolution=resolution_parameter)
labels = louvain.fit_predict(adjacency)
labels_unique, counts = np.unique(labels, return_counts=True)
mod.append(get_modularity(adjacency, labels))
print(labels_unique, counts)
print(get_modularity(adjacency, labels))

Resolution yielding maximum modularity is 1.0999999999999999
[0 1 2 3 4 5] [82 41 36 36 27 19]
0.34641386157660503


In [ ]:
country_communities_df = pd.DataFrame({
    'Country': adjacency_df.index,
    'Community': labels
})

country_communities_df.to_csv("Louvain_MeanAdjMat.csv", index=False)
files.download("Louvain_MeanAdjMat.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# Agriculture

In [ ]:
# Load your adjacency matrix from CSV
adjacency_df = pd.read_csv("Agric_AdjacencyMatrix.csv", index_col=0)  # Assuming row names are in the first column
adjacency = adjacency_df.values  # Extract the numeric values from DataFrame


In [ ]:
resolution_values = np.arange(0.5, 3.1, 0.1).tolist()
mod = []
for r in resolution_values:
  resolution_parameter = r # Adjust the resolution parameter as needed
  louvain = Louvain(resolution=resolution_parameter)
  labels = louvain.fit_predict(adjacency)
  labels_unique, counts = np.unique(labels, return_counts=True)
  mod.append(get_modularity(adjacency, labels))

# Find the maximum value in the list
max_mod = max(mod)

# Find the index of the maximum value in the list
max_index = mod.index(max_mod)
r_max = resolution_values[max_index]

print(f"Resolution yielding maximum modularity is {r_max}")
resolution_parameter = r_max # Adjust the resolution parameter as needed
louvain = Louvain(resolution=resolution_parameter)
labels = louvain.fit_predict(adjacency)
labels_unique, counts = np.unique(labels, return_counts=True)
mod.append(get_modularity(adjacency, labels))
print(labels_unique, counts)
print(get_modularity(adjacency, labels))

Resolution yielding maximum modularity is 0.8999999999999999
[0 1 2 3 4 5] [92 86 44 16  3  1]
0.3278213490591159


In [ ]:
country_communities_df = pd.DataFrame({
    'Country': adjacency_df.index,
    'Community': labels
})

# Output the DataFrame
print(country_communities_df)

                    Country  Community
0               Afghanistan          0
1                   Albania          1
2                   Algeria          1
3            American Samoa          0
4                   Andorra          1
..                      ...        ...
237  Wallis and Futura Isl.          0
238          Western Sahara          1
239                   Yemen          1
240                  Zambia          0
241                Zimbabwe          0

[242 rows x 2 columns]


In [ ]:
country_communities_df.to_csv("Louvain_Agricolture.csv", index=False)
files.download("Louvain_Agricolture.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# Food Product

In [ ]:
# Load your adjacency matrix from CSV
adjacency_df = pd.read_csv("FoodProducts_AdjacencyMatrix.csv", index_col=0)  # Assuming row names are in the first column
adjacency = adjacency_df.values  # Extract the numeric values from DataFrame


In [ ]:
resolution_values = np.arange(0.5, 3.1, 0.1).tolist()
mod = []
for r in resolution_values:
  resolution_parameter = r # Adjust the resolution parameter as needed
  louvain = Louvain(resolution=resolution_parameter)
  labels = louvain.fit_predict(adjacency)
  labels_unique, counts = np.unique(labels, return_counts=True)
  mod.append(get_modularity(adjacency, labels))

# Find the maximum value in the list
max_mod = max(mod)

# Find the index of the maximum value in the list
max_index = mod.index(max_mod)
r_max = resolution_values[max_index]

print(f"Resolution yielding maximum modularity is {r_max}")
resolution_parameter = r_max # Adjust the resolution parameter as needed
louvain = Louvain(resolution=resolution_parameter)
labels = louvain.fit_predict(adjacency)
labels_unique, counts = np.unique(labels, return_counts=True)
mod.append(get_modularity(adjacency, labels))
print(labels_unique, counts)
print(get_modularity(adjacency, labels))

Resolution yielding maximum modularity is 0.9999999999999999
[0 1 2 3 4] [82 65 42 40 15]
0.3571573315448479


In [ ]:
country_communities_df = pd.DataFrame({
    'Country': adjacency_df.index,
    'Community': labels
})

country_communities_df.to_csv("Louvain_FoodProducts.csv", index=False)
files.download("Louvain_FoodProducts.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# Fuels

In [ ]:
# Load your adjacency matrix from CSV
adjacency_df = pd.read_csv("Fuels_AdjacencyMatrix.csv", index_col=0)  # Assuming row names are in the first column
adjacency = adjacency_df.values  # Extract the numeric values from DataFrame


In [ ]:
resolution_values = np.arange(0.5, 3.1, 0.1).tolist()
mod = []
for r in resolution_values:
  resolution_parameter = r # Adjust the resolution parameter as needed
  louvain = Louvain(resolution=resolution_parameter)
  labels = louvain.fit_predict(adjacency)
  labels_unique, counts = np.unique(labels, return_counts=True)
  mod.append(get_modularity(adjacency, labels))

# Find the maximum value in the list
max_mod = max(mod)

# Find the index of the maximum value in the list
max_index = mod.index(max_mod)
r_max = resolution_values[max_index]

print(f"Resolution yielding maximum modularity is {r_max}")
resolution_parameter = r_max # Adjust the resolution parameter as needed
louvain = Louvain(resolution=resolution_parameter)
labels = louvain.fit_predict(adjacency)
labels_unique, counts = np.unique(labels, return_counts=True)
mod.append(get_modularity(adjacency, labels))
print(labels_unique, counts)
print(get_modularity(adjacency, labels))

Resolution yielding maximum modularity is 0.8999999999999999
[0 1 2 3 4] [82 52 49 35 24]
0.4043852803739548


In [ ]:
country_communities_df = pd.DataFrame({
    'Country': adjacency_df.index,
    'Community': labels
})

country_communities_df.to_csv("Louvain_Fuels.csv", index=False)
files.download("Louvain_Fuels.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# Ores

In [ ]:
# Load your adjacency matrix from CSV
adjacency_df = pd.read_csv("OresMets_AdjacencyMatrix.csv", index_col=0)  # Assuming row names are in the first column
adjacency = adjacency_df.values  # Extract the numeric values from DataFrame


In [ ]:
resolution_values = np.arange(0.5, 3.1, 0.1).tolist()
mod = []
for r in resolution_values:
  resolution_parameter = r # Adjust the resolution parameter as needed
  louvain = Louvain(resolution=resolution_parameter)
  labels = louvain.fit_predict(adjacency)
  labels_unique, counts = np.unique(labels, return_counts=True)
  mod.append(get_modularity(adjacency, labels))

# Find the maximum value in the list
max_mod = max(mod)

# Find the index of the maximum value in the list
max_index = mod.index(max_mod)
r_max = resolution_values[max_index]

print(f"Resolution yielding maximum modularity is {r_max}")
resolution_parameter = r_max # Adjust the resolution parameter as needed
louvain = Louvain(resolution=resolution_parameter)
labels = louvain.fit_predict(adjacency)
labels_unique, counts = np.unique(labels, return_counts=True)
mod.append(get_modularity(adjacency, labels))
print(labels_unique, counts)
print(get_modularity(adjacency, labels))

Resolution yielding maximum modularity is 0.8999999999999999
[0 1 2 3] [94 71 39 38]
0.33126065262957133


In [ ]:
country_communities_df = pd.DataFrame({
    'Country': adjacency_df.index,
    'Community': labels
})

country_communities_df.to_csv("Louvain_OresMets.csv", index=False)
files.download("Louvain_OresMets.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# Aggregated

In [ ]:
# Load your adjacency matrix from CSV
adjacency_df = pd.read_csv("Community_sharing_across_products_Python.csv", index_col=0)  # Assuming row names are in the first column
adjacency = adjacency_df.values  # Extract the numeric values from DataFrame


In [ ]:
resolution_values = np.arange(0.5, 3.1, 0.1).tolist()
mod = []
for r in resolution_values:
  resolution_parameter = r # Adjust the resolution parameter as needed
  louvain = Louvain(resolution=resolution_parameter)
  labels = louvain.fit_predict(adjacency)
  labels_unique, counts = np.unique(labels, return_counts=True)
  mod.append(get_modularity(adjacency, labels))
  print(f"Resolution = {r}")
  print(labels_unique, counts)
  print(get_modularity(adjacency, labels))
  print("-------------")
# Find the maximum value in the list
max_mod = max(mod)

# Find the index of the maximum value in the list
max_index = mod.index(max_mod)
r_max = resolution_values[max_index]

print(f"Resolution yielding maximum modularity is {r_max}")
resolution_parameter = r_max # Adjust the resolution parameter as needed
louvain = Louvain(resolution=resolution_parameter)
labels = louvain.fit_predict(adjacency)
labels_unique, counts = np.unique(labels, return_counts=True)
mod.append(get_modularity(adjacency, labels))
print(labels_unique, counts)
print(get_modularity(adjacency, labels))

In [ ]:
resolution_parameter = 1.1 # Adjust the resolution parameter as needed
louvain = Louvain(resolution=resolution_parameter)
labels = louvain.fit_predict(adjacency)
labels_unique, counts = np.unique(labels, return_counts=True)
mod.append(get_modularity(adjacency, labels))
print(labels_unique, counts)
print(get_modularity(adjacency, labels))

[0 1 2 3] [86 59 49 47]
0.33545943470246664


In [ ]:
country_communities_df = pd.DataFrame({
    'Country': adjacency_df.index,
    'Community': labels
})

country_communities_df.to_csv("Louvain_Aggregated.csv", index=False)
files.download("Louvain_Aggregated.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# Multi-Layer Community Detection

In [ ]:
agric = pd.read_csv("Agric_AdjacencyMatrix_Standard.csv", index_col=0, encoding='latin-1')
foodprod = pd.read_csv("FoodProducts_AdjacencyMatrix_Standard.csv", index_col=0, encoding='latin-1')
fuels = pd.read_csv("Fuels_AdjacencyMatrix_Standard.csv", index_col=0, encoding='latin-1')
ores = pd.read_csv("OresMets_AdjacencyMatrix_Standard.csv", index_col=0, encoding='latin-1')

In [ ]:
from igraph import Graph

In [ ]:
# Convert adjacency matrices to igraph Graph objects
graph_agric = Graph.Adjacency((agric.values > 0).tolist(), mode="directed")
graph_foodprod = Graph.Adjacency((foodprod.values > 0).tolist(), mode="directed")
graph_fuels = Graph.Adjacency((fuels.values > 0).tolist(), mode="directed")
graph_ores = Graph.Adjacency((ores.values > 0).tolist(), mode="directed")

# Set vertex names
graph_agric.vs["name"] = agric.index
graph_foodprod.vs["name"] = foodprod.index
graph_fuels.vs["name"] = fuels.index
graph_ores.vs["name"] = ores.index


In [ ]:
agric.index

Index(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Anguila', 'Antarctica', 'Antigua and Barbuda', 'Argentina',
       ...
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
       'Wallis and Futura Isl.', 'Western Sahara', 'Yemen', 'Zambia',
       'Zimbabwe'],
      dtype='object', length=241)

In [ ]:
agric1 = agric.to_numpy()
foodprod1 = foodprod.to_numpy()
fuels1 = fuels.to_numpy()
ores1 = ores.to_numpy()


# Create a directed graph from the adjacency matrix
g_agric = nx.DiGraph(agric1)
g_foodprod = nx.DiGraph(foodprod1)
g_fuels = nx.DiGraph(fuels1)
g_ores = nx.DiGraph(ores1)

In [ ]:
sum_agric = np.sum(agric1)
sum_foodprod = np.sum(foodprod1)
sum_fuels = np.sum(fuels1)
sum_ores = np.sum(ores1)

sum_total = sum_agric+sum_foodprod+sum_fuels+sum_ores

weights = [sum_agric/sum_total,sum_foodprod/sum_total, sum_fuels/sum_total, sum_ores/sum_total]
print(weights)

[0.06709868310239903, 0.17948852114100575, 0.48164316763648835, 0.2717696281201068]


In [ ]:
optimiser = la.Optimiser()

In [ ]:
membership, improv = la.find_partition_multiplex(
                       [graph_agric, graph_foodprod, graph_fuels, graph_ores],
                       la.ModularityVertexPartition)#,
                       #layer_weights=weights)

In [ ]:
country_communities_df = pd.DataFrame({
    'Country': agric.index,
    'Community': membership
})
country_communities_df.to_csv("Generalized_Louvain_Aggregated.csv", index=False)
#files.download("Generalized_Louvain_Aggregated.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
print(improv)
print(country_communities_df)

                    Country  Community
0               Afghanistan          1
1                   Albania          1
2                   Algeria          1
3            American Samoa          3
4                   Andorra          2
..                      ...        ...
236  Wallis and Futura Isl.          3
237          Western Sahara          3
238                   Yemen          1
239                  Zambia          3
240                Zimbabwe          2

[241 rows x 2 columns]
